structname: '{{ .InterfaceName }}'
filename: "{{ .InterfaceName | snakecase }}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/jailtonjunior94/order-aws/pkg/storage:
    config:
      dir: ./pkg/storage/mocks
      pkgname: storageMock
    interfaces:
      StorageClient: {}
  github.com/jailtonjunior94/order-aws/pkg/database:
    config:
      dir: ./pkg/database/mocks
      pkgname: databaseMock
    interfaces:
      DynamoDBClient: {}
  github.com/jailtonjunior94/order-aws/pkg/messaging:
    config:
      dir: ./pkg/messaging/mocks
      pkgname: messagingMock
    interfaces:
      SqsClient: {}
  github.com/jailtonjunior94/order-aws/internal/domain/ports:
    interfaces:
      OrderRepository:
        config:
          dir: ./internal/infrastructure/dynamo/mocks
          pkgname: dynamoMock
