structname: '{{ .InterfaceName }}'
filename: "{{ .InterfaceName | snakecase }}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/jailtonjunior94/order-aws/pkg/storage:
    config:
      dir: ./pkg/storage/mocks
      pkgname: storageMock
    interfaces:
      StorageClient: {}
