services:
  localstack:
    container_name: localstack
    image: localstack/localstack:4.7.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_volume:
